eureka:
  client:
    serviceUrl:
      defaultZone: http://eurake7001.com:7001/eureka/,http://eurake7002.com:7002/eureka/

spring:
  application:
    name: front-end-system
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
server:
  port: 8001
feign:
  httpclient:
    enabled: true
