server:
  port: 7002
eureka:
  instance:
    hostname: eurake7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurake7001.com:7001/eureka/

