server:
  port: 7001
eureka:
  instance:
    hostname: eurake7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurake7002.com:7002/eureka/


